#############################################################################
# Makefile for building: THANG_UI
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  THANG_UI.pro
# Template: app
# Command: /home/nhan/rpi/qt5.15/bin/qmake -o Makefile THANG_UI.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
CXX           = /home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nhan/rpi/sysroot -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nhan/rpi/sysroot -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../qt5.15/include -I../qt5.15/include/QtQuick -I../qt5.15/include/QtGui -I../qt5.15/include/QtQmlModels -I../qt5.15/include/QtQml -I../qt5.15/include/QtNetwork -I../qt5.15/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I../qt5.15/mkspecs/devices/linux-rasp-pi3-g++
QMAKE         = /home/nhan/rpi/qt5.15/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/nhan/rpi/qt5.15/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/nhan/rpi/qt5.15/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = THANG_UI1.0.0
DISTDIR = /home/nhan/rpi/THANG_UI/.tmp/THANG_UI1.0.0
LINK          = /home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/nhan/rpi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5.15/lib -Wl,-rpath-link,/home/nhan/rpi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/nhan/rpi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/nhan/rpi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L=/opt/vc/lib /home/nhan/rpi/qt5.15/lib/libQt5Quick.so /home/nhan/rpi/qt5.15/lib/libQt5Gui.so /home/nhan/rpi/qt5.15/lib/libQt5QmlModels.so /home/nhan/rpi/qt5.15/lib/libQt5Qml.so /home/nhan/rpi/qt5.15/lib/libQt5Network.so /home/nhan/rpi/qt5.15/lib/libQt5Core.so -L/home/nhan/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lGLESv2 -lpthread   
AR            = /home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = 2.png \
		../qt5.15/mkspecs/features/spec_pre.prf \
		../qt5.15/mkspecs/common/unix.conf \
		../qt5.15/mkspecs/common/linux.conf \
		../qt5.15/mkspecs/common/sanitize.conf \
		../qt5.15/mkspecs/common/gcc-base.conf \
		../qt5.15/mkspecs/common/gcc-base-unix.conf \
		../qt5.15/mkspecs/common/g++-base.conf \
		../qt5.15/mkspecs/common/g++-unix.conf \
		../qt5.15/mkspecs/qdevice.pri \
		../qt5.15/mkspecs/features/device_config.prf \
		../qt5.15/mkspecs/devices/common/linux_device_pre.conf \
		../qt5.15/mkspecs/devices/common/linux_device_post.conf \
		../qt5.15/mkspecs/devices/common/linux_arm_device_post.conf \
		../qt5.15/mkspecs/qconfig.pri \
		../qt5.15/mkspecs/modules/qt_lib_3danimation.pri \
		../qt5.15/mkspecs/modules/qt_lib_3danimation_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dcore.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dcore_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dextras.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dextras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dinput.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dinput_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dlogic.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquick.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickextras.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickinput.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickrender.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3drender.pri \
		../qt5.15/mkspecs/modules/qt_lib_3drender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_charts.pri \
		../qt5.15/mkspecs/modules/qt_lib_charts_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_core.pri \
		../qt5.15/mkspecs/modules/qt_lib_core_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_datavisualization.pri \
		../qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_dbus.pri \
		../qt5.15/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_egl_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_gamepad.pri \
		../qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_gui.pri \
		../qt5.15/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_help.pri \
		../qt5.15/mkspecs/modules/qt_lib_help_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_kms_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_location.pri \
		../qt5.15/mkspecs/modules/qt_lib_location_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimedia.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_network.pri \
		../qt5.15/mkspecs/modules/qt_lib_network_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_networkauth.pri \
		../qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_nfc.pri \
		../qt5.15/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_opengl.pri \
		../qt5.15/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioning.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_purchasing.pri \
		../qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qml.pri \
		../qt5.15/mkspecs/modules/qt_lib_qml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmltest.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3d.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3drender.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_repparser.pri \
		../qt5.15/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_scxml.pri \
		../qt5.15/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_sensors.pri \
		../qt5.15/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialbus.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialport.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_sql.pri \
		../qt5.15/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_svg.pri \
		../qt5.15/mkspecs/modules/qt_lib_svg_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_testlib.pri \
		../qt5.15/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt5.15/mkspecs/modules/qt_lib_uitools.pri \
		../qt5.15/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_webchannel.pri \
		../qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_websockets.pri \
		../qt5.15/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_webview.pri \
		../qt5.15/mkspecs/modules/qt_lib_webview_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_widgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_x11extras.pri \
		../qt5.15/mkspecs/modules/qt_lib_x11extras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xml.pri \
		../qt5.15/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5.15/mkspecs/features/qt_functions.prf \
		../qt5.15/mkspecs/features/qt_config.prf \
		../qt5.15/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../qt5.15/mkspecs/features/spec_post.prf \
		../qt5.15/mkspecs/features/exclusive_builds.prf \
		../qt5.15/mkspecs/features/toolchain.prf \
		../qt5.15/mkspecs/features/default_pre.prf \
		../qt5.15/mkspecs/features/resolve_config.prf \
		../qt5.15/mkspecs/features/default_post.prf \
		../qt5.15/mkspecs/features/warn_on.prf \
		../qt5.15/mkspecs/features/qt.prf \
		../qt5.15/mkspecs/features/resources_functions.prf \
		../qt5.15/mkspecs/features/resources.prf \
		../qt5.15/mkspecs/features/moc.prf \
		../qt5.15/mkspecs/features/unix/opengl.prf \
		../qt5.15/mkspecs/features/unix/thread.prf \
		../qt5.15/mkspecs/features/qmake_use.prf \
		../qt5.15/mkspecs/features/file_copies.prf \
		../qt5.15/mkspecs/features/testcase_targets.prf \
		../qt5.15/mkspecs/features/exceptions.prf \
		../qt5.15/mkspecs/features/yacc.prf \
		../qt5.15/mkspecs/features/lex.prf \
		THANG_UI.pro  main.cpp
QMAKE_TARGET  = THANG_UI
DESTDIR       = 
TARGET        = THANG_UI


first: all
####### Build rules

THANG_UI:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: THANG_UI.pro ../qt5.15/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf ../qt5.15/mkspecs/features/spec_pre.prf \
		../qt5.15/mkspecs/common/unix.conf \
		../qt5.15/mkspecs/common/linux.conf \
		../qt5.15/mkspecs/common/sanitize.conf \
		../qt5.15/mkspecs/common/gcc-base.conf \
		../qt5.15/mkspecs/common/gcc-base-unix.conf \
		../qt5.15/mkspecs/common/g++-base.conf \
		../qt5.15/mkspecs/common/g++-unix.conf \
		../qt5.15/mkspecs/qdevice.pri \
		../qt5.15/mkspecs/features/device_config.prf \
		../qt5.15/mkspecs/devices/common/linux_device_pre.conf \
		../qt5.15/mkspecs/devices/common/linux_device_post.conf \
		../qt5.15/mkspecs/devices/common/linux_arm_device_post.conf \
		../qt5.15/mkspecs/qconfig.pri \
		../qt5.15/mkspecs/modules/qt_lib_3danimation.pri \
		../qt5.15/mkspecs/modules/qt_lib_3danimation_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dcore.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dcore_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dextras.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dextras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dinput.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dinput_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dlogic.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquick.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickextras.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickinput.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickrender.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_3drender.pri \
		../qt5.15/mkspecs/modules/qt_lib_3drender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bluetooth.pri \
		../qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_charts.pri \
		../qt5.15/mkspecs/modules/qt_lib_charts_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_core.pri \
		../qt5.15/mkspecs/modules/qt_lib_core_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_datavisualization.pri \
		../qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_dbus.pri \
		../qt5.15/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_egl_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_gamepad.pri \
		../qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_gui.pri \
		../qt5.15/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_help.pri \
		../qt5.15/mkspecs/modules/qt_lib_help_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_kms_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_location.pri \
		../qt5.15/mkspecs/modules/qt_lib_location_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimedia.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_network.pri \
		../qt5.15/mkspecs/modules/qt_lib_network_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_networkauth.pri \
		../qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_nfc.pri \
		../qt5.15/mkspecs/modules/qt_lib_nfc_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_opengl.pri \
		../qt5.15/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioning.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioning_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioningquick.pri \
		../qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_purchasing.pri \
		../qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qml.pri \
		../qt5.15/mkspecs/modules/qt_lib_qml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmltest.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3d.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3drender.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quick_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri \
		../qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_repparser.pri \
		../qt5.15/mkspecs/modules/qt_lib_repparser_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_scxml.pri \
		../qt5.15/mkspecs/modules/qt_lib_scxml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_sensors.pri \
		../qt5.15/mkspecs/modules/qt_lib_sensors_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialbus.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialport.pri \
		../qt5.15/mkspecs/modules/qt_lib_serialport_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_sql.pri \
		../qt5.15/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_svg.pri \
		../qt5.15/mkspecs/modules/qt_lib_svg_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_testlib.pri \
		../qt5.15/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_texttospeech.pri \
		../qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_uiplugin.pri \
		../qt5.15/mkspecs/modules/qt_lib_uitools.pri \
		../qt5.15/mkspecs/modules/qt_lib_uitools_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_webchannel.pri \
		../qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_websockets.pri \
		../qt5.15/mkspecs/modules/qt_lib_websockets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_webview.pri \
		../qt5.15/mkspecs/modules/qt_lib_webview_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_widgets.pri \
		../qt5.15/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_x11extras.pri \
		../qt5.15/mkspecs/modules/qt_lib_x11extras_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xml.pri \
		../qt5.15/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../qt5.15/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5.15/mkspecs/features/qt_functions.prf \
		../qt5.15/mkspecs/features/qt_config.prf \
		../qt5.15/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../qt5.15/mkspecs/features/spec_post.prf \
		../qt5.15/mkspecs/features/exclusive_builds.prf \
		../qt5.15/mkspecs/features/toolchain.prf \
		../qt5.15/mkspecs/features/default_pre.prf \
		../qt5.15/mkspecs/features/resolve_config.prf \
		../qt5.15/mkspecs/features/default_post.prf \
		../qt5.15/mkspecs/features/warn_on.prf \
		../qt5.15/mkspecs/features/qt.prf \
		../qt5.15/mkspecs/features/resources_functions.prf \
		../qt5.15/mkspecs/features/resources.prf \
		../qt5.15/mkspecs/features/moc.prf \
		../qt5.15/mkspecs/features/unix/opengl.prf \
		../qt5.15/mkspecs/features/unix/thread.prf \
		../qt5.15/mkspecs/features/qmake_use.prf \
		../qt5.15/mkspecs/features/file_copies.prf \
		../qt5.15/mkspecs/features/testcase_targets.prf \
		../qt5.15/mkspecs/features/exceptions.prf \
		../qt5.15/mkspecs/features/yacc.prf \
		../qt5.15/mkspecs/features/lex.prf \
		THANG_UI.pro \
		qml.qrc
	$(QMAKE) -o Makefile THANG_UI.pro
../qt5.15/mkspecs/features/spec_pre.prf:
../qt5.15/mkspecs/common/unix.conf:
../qt5.15/mkspecs/common/linux.conf:
../qt5.15/mkspecs/common/sanitize.conf:
../qt5.15/mkspecs/common/gcc-base.conf:
../qt5.15/mkspecs/common/gcc-base-unix.conf:
../qt5.15/mkspecs/common/g++-base.conf:
../qt5.15/mkspecs/common/g++-unix.conf:
../qt5.15/mkspecs/qdevice.pri:
../qt5.15/mkspecs/features/device_config.prf:
../qt5.15/mkspecs/devices/common/linux_device_pre.conf:
../qt5.15/mkspecs/devices/common/linux_device_post.conf:
../qt5.15/mkspecs/devices/common/linux_arm_device_post.conf:
../qt5.15/mkspecs/qconfig.pri:
../qt5.15/mkspecs/modules/qt_lib_3danimation.pri:
../qt5.15/mkspecs/modules/qt_lib_3danimation_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dcore.pri:
../qt5.15/mkspecs/modules/qt_lib_3dcore_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dextras.pri:
../qt5.15/mkspecs/modules/qt_lib_3dextras_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dinput.pri:
../qt5.15/mkspecs/modules/qt_lib_3dinput_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dlogic.pri:
../qt5.15/mkspecs/modules/qt_lib_3dlogic_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquick.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquick_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickanimation.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickextras.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickinput.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickrender.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../qt5.15/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../qt5.15/mkspecs/modules/qt_lib_3drender.pri:
../qt5.15/mkspecs/modules/qt_lib_3drender_private.pri:
../qt5.15/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_bluetooth.pri:
../qt5.15/mkspecs/modules/qt_lib_bluetooth_private.pri:
../qt5.15/mkspecs/modules/qt_lib_bodymovin_private.pri:
../qt5.15/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt5.15/mkspecs/modules/qt_lib_charts.pri:
../qt5.15/mkspecs/modules/qt_lib_charts_private.pri:
../qt5.15/mkspecs/modules/qt_lib_concurrent.pri:
../qt5.15/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt5.15/mkspecs/modules/qt_lib_core.pri:
../qt5.15/mkspecs/modules/qt_lib_core_private.pri:
../qt5.15/mkspecs/modules/qt_lib_datavisualization.pri:
../qt5.15/mkspecs/modules/qt_lib_datavisualization_private.pri:
../qt5.15/mkspecs/modules/qt_lib_dbus.pri:
../qt5.15/mkspecs/modules/qt_lib_dbus_private.pri:
../qt5.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_edid_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_egl_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../qt5.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_gamepad.pri:
../qt5.15/mkspecs/modules/qt_lib_gamepad_private.pri:
../qt5.15/mkspecs/modules/qt_lib_gui.pri:
../qt5.15/mkspecs/modules/qt_lib_gui_private.pri:
../qt5.15/mkspecs/modules/qt_lib_help.pri:
../qt5.15/mkspecs/modules/qt_lib_help_private.pri:
../qt5.15/mkspecs/modules/qt_lib_input_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_kms_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_location.pri:
../qt5.15/mkspecs/modules/qt_lib_location_private.pri:
../qt5.15/mkspecs/modules/qt_lib_multimedia.pri:
../qt5.15/mkspecs/modules/qt_lib_multimedia_private.pri:
../qt5.15/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../qt5.15/mkspecs/modules/qt_lib_multimediawidgets.pri:
../qt5.15/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../qt5.15/mkspecs/modules/qt_lib_network.pri:
../qt5.15/mkspecs/modules/qt_lib_network_private.pri:
../qt5.15/mkspecs/modules/qt_lib_networkauth.pri:
../qt5.15/mkspecs/modules/qt_lib_networkauth_private.pri:
../qt5.15/mkspecs/modules/qt_lib_nfc.pri:
../qt5.15/mkspecs/modules/qt_lib_nfc_private.pri:
../qt5.15/mkspecs/modules/qt_lib_opengl.pri:
../qt5.15/mkspecs/modules/qt_lib_opengl_private.pri:
../qt5.15/mkspecs/modules/qt_lib_openglextensions.pri:
../qt5.15/mkspecs/modules/qt_lib_openglextensions_private.pri:
../qt5.15/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qt5.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_positioning.pri:
../qt5.15/mkspecs/modules/qt_lib_positioning_private.pri:
../qt5.15/mkspecs/modules/qt_lib_positioningquick.pri:
../qt5.15/mkspecs/modules/qt_lib_positioningquick_private.pri:
../qt5.15/mkspecs/modules/qt_lib_printsupport.pri:
../qt5.15/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt5.15/mkspecs/modules/qt_lib_purchasing.pri:
../qt5.15/mkspecs/modules/qt_lib_purchasing_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qml.pri:
../qt5.15/mkspecs/modules/qt_lib_qml_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qmlmodels.pri:
../qt5.15/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qmltest.pri:
../qt5.15/mkspecs/modules/qt_lib_qmltest_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../qt5.15/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../qt5.15/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3d.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3d_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3drender.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3drender_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3dutils.pri:
../qt5.15/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quick_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qt5.15/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quickshapes_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quicktemplates2.pri:
../qt5.15/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qt5.15/mkspecs/modules/qt_lib_quickwidgets.pri:
../qt5.15/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qt5.15/mkspecs/modules/qt_lib_remoteobjects.pri:
../qt5.15/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../qt5.15/mkspecs/modules/qt_lib_repparser.pri:
../qt5.15/mkspecs/modules/qt_lib_repparser_private.pri:
../qt5.15/mkspecs/modules/qt_lib_scxml.pri:
../qt5.15/mkspecs/modules/qt_lib_scxml_private.pri:
../qt5.15/mkspecs/modules/qt_lib_sensors.pri:
../qt5.15/mkspecs/modules/qt_lib_sensors_private.pri:
../qt5.15/mkspecs/modules/qt_lib_serialbus.pri:
../qt5.15/mkspecs/modules/qt_lib_serialbus_private.pri:
../qt5.15/mkspecs/modules/qt_lib_serialport.pri:
../qt5.15/mkspecs/modules/qt_lib_serialport_private.pri:
../qt5.15/mkspecs/modules/qt_lib_service_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_sql.pri:
../qt5.15/mkspecs/modules/qt_lib_sql_private.pri:
../qt5.15/mkspecs/modules/qt_lib_svg.pri:
../qt5.15/mkspecs/modules/qt_lib_svg_private.pri:
../qt5.15/mkspecs/modules/qt_lib_testlib.pri:
../qt5.15/mkspecs/modules/qt_lib_testlib_private.pri:
../qt5.15/mkspecs/modules/qt_lib_texttospeech.pri:
../qt5.15/mkspecs/modules/qt_lib_texttospeech_private.pri:
../qt5.15/mkspecs/modules/qt_lib_theme_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_uiplugin.pri:
../qt5.15/mkspecs/modules/qt_lib_uitools.pri:
../qt5.15/mkspecs/modules/qt_lib_uitools_private.pri:
../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../qt5.15/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../qt5.15/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_webchannel.pri:
../qt5.15/mkspecs/modules/qt_lib_webchannel_private.pri:
../qt5.15/mkspecs/modules/qt_lib_websockets.pri:
../qt5.15/mkspecs/modules/qt_lib_websockets_private.pri:
../qt5.15/mkspecs/modules/qt_lib_webview.pri:
../qt5.15/mkspecs/modules/qt_lib_webview_private.pri:
../qt5.15/mkspecs/modules/qt_lib_widgets.pri:
../qt5.15/mkspecs/modules/qt_lib_widgets_private.pri:
../qt5.15/mkspecs/modules/qt_lib_x11extras.pri:
../qt5.15/mkspecs/modules/qt_lib_x11extras_private.pri:
../qt5.15/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../qt5.15/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../qt5.15/mkspecs/modules/qt_lib_xml.pri:
../qt5.15/mkspecs/modules/qt_lib_xml_private.pri:
../qt5.15/mkspecs/modules/qt_lib_xmlpatterns.pri:
../qt5.15/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../qt5.15/mkspecs/modules/qt_lib_zlib_private.pri:
../qt5.15/mkspecs/features/qt_functions.prf:
../qt5.15/mkspecs/features/qt_config.prf:
../qt5.15/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf:
../qt5.15/mkspecs/features/spec_post.prf:
../qt5.15/mkspecs/features/exclusive_builds.prf:
../qt5.15/mkspecs/features/toolchain.prf:
../qt5.15/mkspecs/features/default_pre.prf:
../qt5.15/mkspecs/features/resolve_config.prf:
../qt5.15/mkspecs/features/default_post.prf:
../qt5.15/mkspecs/features/warn_on.prf:
../qt5.15/mkspecs/features/qt.prf:
../qt5.15/mkspecs/features/resources_functions.prf:
../qt5.15/mkspecs/features/resources.prf:
../qt5.15/mkspecs/features/moc.prf:
../qt5.15/mkspecs/features/unix/opengl.prf:
../qt5.15/mkspecs/features/unix/thread.prf:
../qt5.15/mkspecs/features/qmake_use.prf:
../qt5.15/mkspecs/features/file_copies.prf:
../qt5.15/mkspecs/features/testcase_targets.prf:
../qt5.15/mkspecs/features/exceptions.prf:
../qt5.15/mkspecs/features/yacc.prf:
../qt5.15/mkspecs/features/lex.prf:
THANG_UI.pro:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile THANG_UI.pro

qmake_all: FORCE


all: Makefile THANG_UI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../qt5.15/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../qt5.15/bin/rcc \
		main.qml \
		2.png
	/home/nhan/rpi/qt5.15/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../qt5.15/mkspecs/features/data/dummy.cpp
	/home/nhan/rpi/tools/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nhan/rpi/sysroot -O2 -Wall -Wextra -dM -E -o moc_predefs.h ../qt5.15/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../qt5.15/include/QtGui/QGuiApplication \
		../qt5.15/include/QtGui/qguiapplication.h \
		../qt5.15/include/QtGui/qtguiglobal.h \
		../qt5.15/include/QtCore/qglobal.h \
		../qt5.15/include/QtCore/qconfig-bootstrapped.h \
		../qt5.15/include/QtCore/qconfig.h \
		../qt5.15/include/QtCore/qtcore-config.h \
		../qt5.15/include/QtCore/qsystemdetection.h \
		../qt5.15/include/QtCore/qprocessordetection.h \
		../qt5.15/include/QtCore/qcompilerdetection.h \
		../qt5.15/include/QtCore/qtypeinfo.h \
		../qt5.15/include/QtCore/qsysinfo.h \
		../qt5.15/include/QtCore/qlogging.h \
		../qt5.15/include/QtCore/qflags.h \
		../qt5.15/include/QtCore/qatomic.h \
		../qt5.15/include/QtCore/qbasicatomic.h \
		../qt5.15/include/QtCore/qatomic_bootstrap.h \
		../qt5.15/include/QtCore/qgenericatomic.h \
		../qt5.15/include/QtCore/qatomic_cxx11.h \
		../qt5.15/include/QtCore/qatomic_msvc.h \
		../qt5.15/include/QtCore/qglobalstatic.h \
		../qt5.15/include/QtCore/qmutex.h \
		../qt5.15/include/QtCore/qnumeric.h \
		../qt5.15/include/QtCore/qversiontagging.h \
		../qt5.15/include/QtGui/qtgui-config.h \
		../qt5.15/include/QtCore/qcoreapplication.h \
		../qt5.15/include/QtCore/qstring.h \
		../qt5.15/include/QtCore/qchar.h \
		../qt5.15/include/QtCore/qbytearray.h \
		../qt5.15/include/QtCore/qrefcount.h \
		../qt5.15/include/QtCore/qnamespace.h \
		../qt5.15/include/QtCore/qarraydata.h \
		../qt5.15/include/QtCore/qstringliteral.h \
		../qt5.15/include/QtCore/qstringalgorithms.h \
		../qt5.15/include/QtCore/qstringview.h \
		../qt5.15/include/QtCore/qstringbuilder.h \
		../qt5.15/include/QtCore/qobject.h \
		../qt5.15/include/QtCore/qobjectdefs.h \
		../qt5.15/include/QtCore/qobjectdefs_impl.h \
		../qt5.15/include/QtCore/qlist.h \
		../qt5.15/include/QtCore/qalgorithms.h \
		../qt5.15/include/QtCore/qiterator.h \
		../qt5.15/include/QtCore/qhashfunctions.h \
		../qt5.15/include/QtCore/qpair.h \
		../qt5.15/include/QtCore/qvector.h \
		../qt5.15/include/QtCore/qcontainertools_impl.h \
		../qt5.15/include/QtCore/qpoint.h \
		../qt5.15/include/QtCore/qbytearraylist.h \
		../qt5.15/include/QtCore/qstringlist.h \
		../qt5.15/include/QtCore/qregexp.h \
		../qt5.15/include/QtCore/qstringmatcher.h \
		../qt5.15/include/QtCore/qcoreevent.h \
		../qt5.15/include/QtCore/qscopedpointer.h \
		../qt5.15/include/QtCore/qmetatype.h \
		../qt5.15/include/QtCore/qvarlengtharray.h \
		../qt5.15/include/QtCore/qcontainerfwd.h \
		../qt5.15/include/QtCore/qobject_impl.h \
		../qt5.15/include/QtCore/qeventloop.h \
		../qt5.15/include/QtGui/qwindowdefs.h \
		../qt5.15/include/QtGui/qwindowdefs_win.h \
		../qt5.15/include/QtGui/qinputmethod.h \
		../qt5.15/include/QtCore/qlocale.h \
		../qt5.15/include/QtCore/qvariant.h \
		../qt5.15/include/QtCore/qmap.h \
		../qt5.15/include/QtCore/qdebug.h \
		../qt5.15/include/QtCore/qhash.h \
		../qt5.15/include/QtCore/qtextstream.h \
		../qt5.15/include/QtCore/qiodevice.h \
		../qt5.15/include/QtCore/qset.h \
		../qt5.15/include/QtCore/qcontiguouscache.h \
		../qt5.15/include/QtCore/qsharedpointer.h \
		../qt5.15/include/QtCore/qshareddata.h \
		../qt5.15/include/QtCore/qsharedpointer_impl.h \
		../qt5.15/include/QtCore/qsize.h \
		../qt5.15/include/QtCore/qmargins.h \
		../qt5.15/include/QtQml/QQmlApplicationEngine \
		../qt5.15/include/QtQml/qqmlapplicationengine.h \
		../qt5.15/include/QtQml/qqmlengine.h \
		../qt5.15/include/QtCore/qurl.h \
		../qt5.15/include/QtCore/qurlquery.h \
		../qt5.15/include/QtQml/qjsengine.h \
		../qt5.15/include/QtQml/qjsvalue.h \
		../qt5.15/include/QtQml/qtqmlglobal.h \
		../qt5.15/include/QtQml/qtqml-config.h \
		../qt5.15/include/QtNetwork/qtnetworkglobal.h \
		../qt5.15/include/QtNetwork/qtnetwork-config.h \
		../qt5.15/include/QtQml/qqmldebug.h \
		../qt5.15/include/QtQml/qqml.h \
		../qt5.15/include/QtQml/qqmlprivate.h \
		../qt5.15/include/QtQml/qqmlparserstatus.h \
		../qt5.15/include/QtQml/qqmllist.h \
		../qt5.15/include/QtQml/qqmlpropertyvaluesource.h \
		../qt5.15/include/QtCore/qpointer.h \
		../qt5.15/include/QtCore/qmetaobject.h \
		../qt5.15/include/QtQml/qqmlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/THANG_UI/bin || mkdir -p $(INSTALL_ROOT)/opt/THANG_UI/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/THANG_UI/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/THANG_UI/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/THANG_UI/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/THANG_UI/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

